set nocompatible
set clipboard=unnamedplus
set encoding=utf-8
syntax on
filetype plugin indent on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'scrooloose/nerdtree'
Plugin 'mru.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'kchmck/vim-coffee-script'
Plugin 'lervag/vimtex'
Plugin 'easymotion/vim-easymotion'
Plugin 'edkolev/tmuxline.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-notes'
Plugin 'dmdque/solidity.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'rking/ag.vim'
Plugin 'konfekt/fastfold'
Plugin 'elzr/vim-json'
Plugin 'danro/rename.vim'
Plugin 'stephpy/vim-yaml'
Plugin 'farmergreg/vim-lastplace'
Plugin 'PeterRincker/vim-argumentative'
Plugin 'ryanoasis/vim-devicons'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'gavocanov/vim-js-indent'
Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'
Plugin 'neoclide/coc.nvim'
Plugin 'hashivim/vim-terraform'
Plugin 'knsh14/vim-github-link'
Plugin 'fatih/vim-hclfmt'
Plugin 'hjson/vim-hjson'
Plugin 'rebelot/kanagawa.nvim'
Plugin 'lewis6991/gitsigns.nvim'
Plugin 'sindrets/diffview.nvim'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'fatih/vim-go'
Plugin 'nvim-lua/plenary.nvim'
Plugin 'nvim-telescope/telescope.nvim', { 'tag': '0.1.8' }
Plugin 'neovim/nvim-lspconfig'
Plugin 'mechatroner/rainbow_csv'
Plugin 'towolf/vim-helm'

call vundle#end()

colorscheme kanagawa

" Mappings
inoremap jk <ESC>
:imap <D-v> ^O:set paste<Enter>^R+^O:set nopaste<Enter>

" Text settings
set nowrap
set shiftwidth=4
set tabstop=4
set softtabstop=0
set backspace=indent,eol,start
set autoindent
set copyindent
set shiftround
set showmatch
set ignorecase
set smartcase
set smarttab
set expandtab
set hlsearch
set incsearch
set wrap
set linebreak
set nolist
set laststatus=2
set relativenumber
set autoread
set cursorline
set undofile
au CursorHold * checktime
autocmd BufWritePre * StripWhitespace
autocmd FileType typescript setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2 expandtab

" Get rid of backup files
set nobackup
set noswapfile

" Autocomplete with coc
let g:coc_global_extensions = [
  \ 'coc-pairs',
  \ 'coc-python',
  \ 'coc-tsserver',
  \ ]
let g:coc_disable_startup_warning = 1
let g:terraform_fmt_on_save=1
let g:terraform_align=1
autocmd BufWritePost *.hcl silent! execute '!terraform fmt %' | edit

set hidden
set updatetime=300
set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
" Use <c-space> to trigger completion.
inoremap <silent><expr> <Nul> coc#refresh()

command! -nargs=0 Prettier :CocCommand prettier.formatFile

" Remap for rename current word
nmap <C-f> <Plug>(coc-rename)

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" Or use `complete_info` if your vim support it, like:
" inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Airline settings
let g:airline_powerline_fonts = 1
let g:tmuxline_powerline_separators = 1

let g:lightline = {
  \   'colorscheme': 'one',
  \   'active': {
  \     'left':[ [ 'mode', 'paste' ],
  \              [ 'readonly', 'filename', 'modified']
  \     ],
  \     'right':[ ['lineinfo'],
  \               ['percent'],
  \               ['fileformat', 'fileencoding', 'filetype'] ]
  \   },
	\   'component': {
	\     'lineinfo': ' %3l:%-2v',
	\   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head',
  \     'filename': 'LightlineFilename',
  \   }
  \ }

function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return path[len(root)+1:]
  endif
  return expand('%')
endfunction

let g:lightline.subseparator = {
	\   'left': '', 'right': ''
\}

set guioptions-=e  " Don't use GUI tabline

let g:tmuxline_preset = {
      \'a'    : '#S',
      \'b'    : '#[fg=colour255]#(~/.tmux/spotify.sh)',
      \'c'    : '#(~/.tmux/weather.sh)',
      \'win'  : '#I #W#{?@claude_pending, #[fg=colour208]✱#[default],}',
      \'cwin' : '#I #W#{?@claude_pending, #[fg=colour208]✱#[fg=colour231]#[bold],}',
      \'x'    : '%A, %B %e %Y',
      \'y'    : '%I:%M:%S %p',
      \'z'    : '#(whoami)'}



" NERDTree settings
map <C-n> :NERDTreeToggle<CR> " Map ctrl-n to NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

set wildignore+=**/node_modules/**,**/package-lock.json,**/virtualenv_run/**

set splitbelow
set splitright
set relativenumber

" Mark json files as type json -.-
au BufRead,BufNewFile *.json* set filetype=json

" No more :set paste/:set nopaste!
function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin()
    set pastetoggle=<Esc>[201~
    set paste
    return ""
endfunction

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

" Tmux-like window resizing
function! IsEdgeWindowSelected(direction)
  let l:curwindow = winnr()
  exec "wincmd ".a:direction
  let l:result = l:curwindow == winnr()
  if (!l:result)
    " Go back to the previous window
    exec l:curwindow."wincmd w"
  endif
  return l:result
endfunction

function! GetAction(direction)
    let l:keys = ['h', 'j', 'k', 'l']
    let l:actions = ['vertical resize -', 'resize +', 'resize -', 'vertical resize +']
    return get(l:actions, index(l:keys, a:direction))
endfunction

function! GetOpposite(direction)
    let l:keys = ['h', 'j', 'k', 'l']
    let l:opposites = ['l', 'k', 'j', 'h']
    return get(l:opposites, index(l:keys, a:direction))
endfunction

function! TmuxResize(direction, amount)
    if (a:direction == 'j' || a:direction == 'l')
        if IsEdgeWindowSelected(a:direction)
            let l:opposite = GetOpposite(a:direction)
            let l:curwindow = winnr()
            exec 'wincmd '.l:opposite
            let l:action = GetAction(a:direction)
            exec l:action.a:amount
            exec l:curwindow.'wincmd w'
            return
        endif
    " < ^
    elseif (a:direction == 'h' || a:direction == 'k')
        let l:opposite = GetOpposite(a:direction)
        if IsEdgeWindowSelected(l:opposite)
            let l:curwindow = winnr()
            exec 'wincmd '.a:direction
            let l:action = GetAction(a:direction)
            exec l:action.a:amount
            exec l:curwindow.'wincmd w'
            return
        endif
    endif

    let l:action = GetAction(a:direction)
    exec l:action.a:amount
endfunction

" folding properties
let g:SimpylFold_docstring_preview = 0
set foldlevelstart=1

" move between vim splits
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h

" resize vim splits
nnoremap <C-W>h :call TmuxResize('h', 10)<CR>
nnoremap <C-W>j :call TmuxResize('j', 10)<CR>
nnoremap <C-W>k :call TmuxResize('k', 10)<CR>
nnoremap <C-W>l :call TmuxResize('l', 10)<CR>

" Ag settings
nmap <C-s> :Ag "def <cword>" . <CR>

" Buffer settings
command Bd bp\|bd \#
nnoremap <silent> <C-z> :bn<CR>
nnoremap <silent> <C-x> :bp<CR>

nnoremap <C-,> :call search('^'. matchstr(getline('.'), '\(^\s*\)') .'\%<' . line('.') . 'l\S', 'be')<CR>
nnoremap <C-.> :call search('^'. matchstr(getline('.'), '\(^\s*\)') .'\%>' . line('.') . 'l\S', 'e')<CR>

" Telescope
nnoremap ff <cmd>Telescope find_files<cr>
nnoremap fg <cmd>Telescope live_grep<cr>
nnoremap fb <cmd>Telescope buffers<cr>
nnoremap fh <cmd>Telescope help_tags<cr>

" reload vimrc
augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

lua << EOF
require('lspconfig').yamlls.setup({
  filetypes = { "yaml", "yaml.docker-compose" },  -- exclude "helm" filetype
  on_attach = function(client, bufnr)
    -- Detach yamlls if the file is in a helm templates directory
    local path = vim.api.nvim_buf_get_name(bufnr)
    if path:match("/templates/") then
      vim.defer_fn(function()
        vim.lsp.buf_detach_client(bufnr, client.id)
      end, 100)
    end
  end,
  settings = {
    yaml = {
      validate = true,
      completion = true,
      hover = true,
      schemaStore = {
        enable = true,
      },
      schemas = {
        kubernetes = "*.yaml",
      },
      schemaDownload = { enable = true },
      enableSchemaRequest = true,  -- enables #:schema support
    }
  }
})
EOF

lua << EOF
require('lspconfig').taplo.setup({})
EOF


autocmd BufRead,BufNewFile */templates/*.yaml set filetype=helm
autocmd BufRead,BufNewFile */templates/*.tpl set filetype=helm
autocmd BufRead,BufNewFile */templates/**/*.yaml set filetype=helm
autocmd BufRead,BufNewFile */templates/**/*.tpl set filetype=helm

lua << EOF
vim.api.nvim_create_autocmd("BufReadPost", {
  callback = function(args)
    local bufnr = args.buf
    local ft = vim.bo[bufnr].filetype
    local path = vim.api.nvim_buf_get_name(bufnr)

    -- Disable diagnostics for Helm templates
    if (ft == "helm" or ft == "yaml") and path:match("/templates/") then
      vim.diagnostic.disable(bufnr)
      vim.defer_fn(function()
        vim.diagnostic.reset(nil, bufnr)
      end, 500)
    end
  end,
})
EOF
